name: Terraform CI/CD

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Linux Commands
        run: |
          echo "whoami -->" 
          whoami
